name: python-bindings

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up uv
        uses: astral-sh/setup-uv@v4

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('autonomi/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            autonomi/.venv
          key: ${{ runner.os }}-uv-${{ hashFiles('autonomi/uv.lock', 'autonomi/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Build and test
        shell: bash
        working-directory: autonomi
        run: |
          uv venv
          uv sync --locked
          uv run python -V
          uv run pip install -U maturin pytest
          uv run maturin develop --uv
          uv run pytest tests/python/test_bindings.py -q
